<?php
session_start();
include 'Includes/dbconn.php';
include 'Includes/Function.php';
//Storing User From Session Variable
if (isset($_SESSION['uid'])) { 
  $user_id = $_SESSION['uid'];
}
if(isset($_POST['DaysUpdate'])){
     $sql="UPDATE `cart` SET `days`='{$_POST['Days']}' WHERE `id`='{$_POST['cartid']}'";
     if ($Result= mysqli_query($conn, $sql)) {
         echo "Done";
      header('location:Cart.php');  
    }
}


//Function For AutoGenerated Order Number
function AutoGeneratedOrderNumber($OrderNumber)
        {
            $Year = date('y');
            $Month = date('m');
            #Store Constant,Year and month in string
            $Fixed_Str = "EE" . $Year . $Month;


            $OrderDone = true;
            if ($OrderDone) {
                $OrderId_Str = (string)$OrderNumber;
                if (strlen($OrderId_Str) == 1) {
                    $OrderId_Str = "00000" . $OrderId_Str;
                }
                if (strlen($OrderId_Str) == 2) {
                    $OrderId_Str = "0000" . $OrderId_Str;
                }
                if (strlen($OrderId_Str) == 3) {
                    $OrderId_Str = "000" . $OrderId_Str;
                }
                if (strlen($OrderId_Str) == 4) {
                    $OrderId_Str = "00" . $OrderId_Str;
                }
                if (strlen($OrderId_Str) == 5) {
                    $OrderId_Str = "0" . $OrderId_Str;
                }

                $AutoGenratedOrderNumber = $Fixed_Str . $OrderId_Str;
                return $AutoGenratedOrderNumber;
            }
}




//If User Press Remove From Cart Button
if(isset($_REQUEST['Action'])){
    if ($_REQUEST['Action'] == 'Remove') {
        $product_id = $_GET['Product_id'];
        RemoveCartItem($product_id, $user_id);
    }
}


//If User Press Delete All cart Item
if ($_REQUEST['Action'] == 'DeleteAllCartItem') {
    $sql = "DELETE FROM `cart` WHERE `u_id`='$user_id'";
    if ($Result = mysqli_query($conn, $sql)) {
        header('location:cart.php');
    }
}

//For Updating Quantity of Cart Product
if (isset($_POST['UpdateQuantity'])) {
    echo "Hello".$_POST['Days'];
}


// //For Order of Cart Product
if ($_REQUEST['Action'] == 'Order') {
    $cart_id = $_GET['cart_id'];
    $sql = "SELECT * FROM `cart` INNER JOIN products ON products.product_id=cart.p_id INNER JOIN users ON users.user_id=cart.u_id WHERE id='$cart_id'";
    if ($run = mysqli_query($conn, $sql)) {
        $row = mysqli_fetch_assoc($run);

        $Client_ID = $row['u_id'];
        $Product_ID = $row['p_id'];
        $Product_Price = $_GET['subtotal'];
        // $Product_CGST = ($Product_Price * 6) / 100;
        // $Product_SGST = ($Product_Price * 6) / 100;
        // $Product_Total_Price = $Product_Price + $Product_CGST + $Product_SGST;
        $Renting_Days = $row['days'];
        // $Client_Shipping_Address = $row['Client_Address'];
        // $Client_Billing_Address = $row['Client_Address'];
        // $temp = mysqli_query($conn, "SELECT MAX(id) FROM client_order");
        // $last_order_id = mysqli_fetch_assoc($temp);
        // $Tempnumber = (int)$last_order_id['MAX(id)'] + 1;
        // $Order_Id = AutoGeneratedOrderNumber($Tempnumber);
        // $Order_Date = date("m/d/Y h:i: a", time());

        $sql2 = "INSERT INTO `order_detail`(`p_id`, `u_id`,`rent_days`,`order_status`) VALUES ('$Product_ID','$Client_ID','$Renting_Days','$Product_Price')";
        if ($Result2 = mysqli_query($conn, $sql2)) {

            $sql3 = "DELETE FROM `cart` WHERE `id`= '$cart_id'";
            $Result3 = mysqli_query($conn, $sql3);
            header('location:cart.php');
        }
    }
}
?>

